# docker compose file for base notebook
version: '3.1'

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        http_proxy:
        https_proxy:
        ftp_proxy:
        JUPYTERHUB_VERSION: ${JUPYTERHUB_VERSION}
        DOCKER_NOTEBOOK_IMAGE: ${DOCKER_NOTEBOOK_IMAGE}
    image: ${LOCAL_NOTEBOOK_IMAGE}
    env_file: .env
